# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests, datetime


class Ui_MainWindow(object):
    def result(self,date):
        url = "https://open.neis.go.kr/hub/mealServiceDietInfo"
        para = {
            "KEY": "05789270567a48d48024fc06439a91b1",
            "Type": "json",
            "ATPT_OFCDC_SC_CODE": "J10",
            "SD_SCHUL_CODE": "7530137",
            "MLSV_YMD": date[:6]
        }
        res = requests.get(url, params=para)
        meal_data = res.json()
        meell = list(meal_data['mealServiceDietInfo'][1].values())[0]
        for i in meell:
            if i['MLSV_YMD'] == date:
                return i["DDISH_NM"].split("<br/>")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(286, 240)
        self.group = QtWidgets.QGroupBox("히히")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.re = QtWidgets.QTextBrowser(self.centralwidget)
        self.re.setGeometry(QtCore.QRect(10, 10, 261, 192))
        self.re.setObjectName("textBrowser")
        self.years = QtWidgets.QComboBox(self.centralwidget)
        self.years.setGeometry(QtCore.QRect(10, 210, 81, 22))
        self.years.setObjectName("years")
        self.years.addItems(['2022','2023'])
        self.mounth = QtWidgets.QComboBox(self.centralwidget)
        self.mounth.setGeometry(QtCore.QRect(100, 210, 81, 22))
        self.mounth.setObjectName("mounth")
        self.mounth.addItems(map(lambda x:str(x),(range(1,13))))
        self.date = QtWidgets.QComboBox(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(190, 210, 81, 22))
        self.date.setObjectName("date")
        self.date.currentIndexChanged.connect(self.act)
        self.years.currentIndexChanged.connect(self.act)
        self.mounth.currentIndexChanged.connect(self.act)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def set_date(self,month):
        self.date.clear()
        self.date.addItems(map(lambda x:str(x),(range(28))))

    def act(self):
        list(map(lambda x:self.re.append(x),self.result("20230911")))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
